/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agenda;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kauan.user
 */
public class FormAgenda extends javax.swing.JFrame {
    
    ArrayList<Compromisso> agenda;
    ArrayList<Notificacao> notificacao = new ArrayList<>();
    
    SimpleDateFormat auxDateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    
    DefaultListModel ListModelCompromisso = new DefaultListModel<Compromisso>();
    DefaultListModel ListModelNotificacao = new DefaultListModel<Notificacao>();
    
    
    /**
     * Creates new form FormAgenda
     */
    public FormAgenda(ArrayList<Compromisso> agenda) {
        this.agenda = agenda;
        initComponents();
        Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jListCompromissos = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldTempo = new javax.swing.JTextField();
        jFormattedTextFieldUnidade = new javax.swing.JTextField();
        jFormattedTextFieldTipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonEditarNotificacao = new javax.swing.JButton();
        jButtonExcluirNotificacao = new javax.swing.JButton();
        SalvarNotificacao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNotificacoes = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabelDataInicio = new javax.swing.JLabel();
        jLabelDataFim = new javax.swing.JLabel();
        jFormattedTextFieldDataInicio = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataFim = new javax.swing.JFormattedTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditarCompromisso = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListCompromissos.setName("jListCompromissos"); // NOI18N
        jListCompromissos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCompromissosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListCompromissos);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Tempo");

        jLabel2.setText("Unidade");

        jLabel3.setText("Tipo");

        jButtonEditarNotificacao.setText("Editar");
        jButtonEditarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarNotificacaoActionPerformed(evt);
            }
        });

        jButtonExcluirNotificacao.setText("Excluir");
        jButtonExcluirNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirNotificacaoActionPerformed(evt);
            }
        });

        SalvarNotificacao.setText("Salvar");
        SalvarNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarNotificacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextFieldTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(SalvarNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldUnidade)
                    .addComponent(jLabel2)
                    .addComponent(jButtonEditarNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextFieldTipo)
                    .addComponent(jLabel3)
                    .addComponent(jButtonExcluirNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jFormattedTextFieldTempo)
                    .addComponent(jFormattedTextFieldUnidade)
                    .addComponent(jFormattedTextFieldTipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirNotificacao)
                    .addComponent(SalvarNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );

        jListNotificacoes.setName("jListNotificacoes"); // NOI18N
        jListNotificacoes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNotificacoesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListNotificacoes);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabelTitulo.setText("Título");

        jLabelDescricao.setText("Descrição");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jLabelDataInicio.setText("Data Início");

        jLabelDataFim.setText("Data Fim");

        try {
            jFormattedTextFieldDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditarCompromisso.setText("Editar");
        jButtonEditarCompromisso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCompromissoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonEditarCompromisso, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDataInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataFim)
                            .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescricao)
                            .addComponent(jLabelTitulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataFim)
                    .addComponent(jLabelDataInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditarCompromisso))
                .addContainerGap())
        );

        label1.setText("Notificações");

        label2.setText("Compromissos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        Salvar();
        Listar();
        LimparCampos();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarCompromissoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCompromissoActionPerformed
            
        Compromisso compromisso = jListCompromissos.getSelectedValue();
        
        try{
            compromisso.setTitulo(jTextFieldTitulo.getText());
            compromisso.setDescricao(jTextAreaDescricao.getText());
            compromisso.setHoraInicio(auxDateFormat.parse(jFormattedTextFieldDataInicio.getText()));
            compromisso.setHoraFim(auxDateFormat.parse(jFormattedTextFieldDataFim.getText()));        
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Erro ao editar compromisso!");
        }

        Listar();
        LimparCampos();
    }//GEN-LAST:event_jButtonEditarCompromissoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        agenda.remove(jListCompromissos.getSelectedIndex());
        
        Listar();
        LimparCampos();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void SalvarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarNotificacaoActionPerformed
        Notificacao notificacao = new Notificacao();
        
        notificacao.setTempo(Byte.parseByte(jFormattedTextFieldTempo.getText()));
        notificacao.setTipo(jFormattedTextFieldUnidade.getText().charAt(0));
        notificacao.setUnidade(jFormattedTextFieldTipo.getText());   
        
        Compromisso compromisso = jListCompromissos.getSelectedValue();
        
        compromisso.notificacao.add(notificacao);
        
        ListModelNotificacao.clear();
        ListModelNotificacao.addAll(compromisso.getNotificacao());
        
        Listar();
        LimparCampos();
    }//GEN-LAST:event_SalvarNotificacaoActionPerformed

    private void jListCompromissosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCompromissosValueChanged
        Compromisso auxCompromisso = jListCompromissos.getSelectedValue();
        
        if(auxCompromisso != null){
            
            jTextFieldTitulo.setText(auxCompromisso.getTitulo());
            jTextAreaDescricao.setText(auxCompromisso.getDescricao());
            jFormattedTextFieldDataInicio.setText(auxDateFormat.format(auxCompromisso.getHoraInicio()));
            jFormattedTextFieldDataFim.setText(auxDateFormat.format(auxCompromisso.getHoraInicio()));
            
            ListModelNotificacao.clear();
            ListModelNotificacao.addAll(auxCompromisso.getNotificacao());
        }
        LimparNotificacao();
    }//GEN-LAST:event_jListCompromissosValueChanged

    private void LimparNotificacao(){
        
        jFormattedTextFieldTempo.setText("");
        jFormattedTextFieldUnidade.setText("");
        jFormattedTextFieldTipo.setText("");
    }
    
    
    private void jListNotificacoesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNotificacoesValueChanged
        Notificacao notific = jListNotificacoes.getSelectedValue();
        
        if(notific != null)
        {
            jFormattedTextFieldTempo.setText(String.valueOf(notific.getTempo()));
            jFormattedTextFieldUnidade.setText(notific.getUnidade());
            jFormattedTextFieldTipo.setText(String.valueOf(notific.getTipo()));            
        }
    }//GEN-LAST:event_jListNotificacoesValueChanged

    private void jButtonEditarNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarNotificacaoActionPerformed
        Notificacao notific = jListNotificacoes.getSelectedValue();
        
        notific.setTempo(Byte.parseByte(jFormattedTextFieldTempo.getText()));
        notific.setUnidade(jFormattedTextFieldUnidade.getText());  
        notific.setTipo(jFormattedTextFieldTipo.getText().charAt(0)); 
        
        Listar();
        LimparCampos();
    }//GEN-LAST:event_jButtonEditarNotificacaoActionPerformed

    private void jButtonExcluirNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirNotificacaoActionPerformed
        Compromisso compromisso = jListCompromissos.getSelectedValue();
        compromisso.notificacao.remove(jListNotificacoes.getSelectedIndex());
        
        ListModelNotificacao.clear();
        ListModelNotificacao.addAll(compromisso.getNotificacao());

        Listar();
        LimparCampos();
    }//GEN-LAST:event_jButtonExcluirNotificacaoActionPerformed

    private void Salvar(){
        try {
            // realiza a leitura dos valores da tela, e as conversões necessárias
            String auxTitulo = jTextFieldTitulo.getText();
            String auxDescricao = jTextAreaDescricao.getText();
            Date auxDataInicio = auxDateFormat.parse(jFormattedTextFieldDataInicio.getText());
            Date auxDataFim = auxDateFormat.parse(jFormattedTextFieldDataFim.getText());
            // cria o objeto do tipo compromisso
            var auxCompromisso = new Compromisso( auxTitulo, auxDescricao, auxDataInicio, auxDataFim );
            // adiciona no array agenda
            agenda.add( auxCompromisso );
        } catch (ParseException x) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar compromisso!");
        }               
    }
    
    private void Listar(){
        ListModelCompromisso.clear();
        ListModelCompromisso.addAll(agenda);
        
        jListCompromissos.setModel(ListModelCompromisso);
        jListNotificacoes.setModel(ListModelNotificacao);  
    }
    
    private void LimparCampos(){
        
        jTextFieldTitulo.setText("");
        jTextAreaDescricao.setText("");
        jFormattedTextFieldDataInicio.setText("");
        jFormattedTextFieldDataFim.setText("");        
        
        jFormattedTextFieldTempo.setText("");
        jFormattedTextFieldUnidade.setText("");
        jFormattedTextFieldTipo.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalvarNotificacao;
    private javax.swing.JButton jButtonEditarCompromisso;
    private javax.swing.JButton jButtonEditarNotificacao;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirNotificacao;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataFim;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataInicio;
    private javax.swing.JTextField jFormattedTextFieldTempo;
    private javax.swing.JTextField jFormattedTextFieldTipo;
    private javax.swing.JTextField jFormattedTextFieldUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDataFim;
    private javax.swing.JLabel jLabelDataInicio;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<Compromisso> jListCompromissos;
    private javax.swing.JList<Notificacao> jListNotificacoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldTitulo;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
